
vectara:
  corpus_id: 8
  customer_id: 566695243
  reindex: true

crawling:
  crawler_type: website

website_crawler:
  urls: ["https://handbook.gitlab.com/handbook/"]
  delay: 1
  pages_source: sitemap
  pos_regex: [".*"]
  extraction: playwright
  ray_workers: 0
